name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up JDK (Android Gradle Plugin usually needs Java 17)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Generate Gradle wrapper (since it's missing in repo)
      - name: Generate Gradle Wrapper
        working-directory: sourcecode
        run: gradle wrapper

      # Make gradlew executable
      - name: Grant execute permission for gradlew
        working-directory: sourcecode
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        working-directory: sourcecode
        run: ./gradlew assembleDebug

      # Upload artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: sourcecode/app/build/outputs/apk/debug/*.apk
